# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'bosmare.github.io'
baseurl: ''
title: 'Lempeä Liekki'
description: 'Lämpöä ja hyvinvointia'
permalink: pretty
logo: "/assets/GentleFlame.svg"

# Header nav
navigation_header:
- title: Etusivu
  url: /

# Footer nav
navigation_footer:
- title: Liekki
