# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'bosmare.github.io'
baseurl: ''
title: 'Lempeä Liekki'
description: 'Lämpöä ja hyvinvointia'
permalink: pretty
logo: "/assets/logos/logo.svg"

# Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo16.png'
  32: '/assets/logos/logo32.png'
  96: '/assets/logos/logo96.png'
  120: '/assets/logos/logo120.png'
  144: '/assets/logos/logo144.png'
  180: '/assets/logos/logo180.png'
  512: '/assets/logos/logo512.png'
  1024: '/assets/logos/logo1024.png'

# Header nav
navigation_header:
- title: Etusivu
  url: /
- title: Ajanvaraus
  url: /ajanvaraus
- title: Yhteystiedot
  url: /yhteystiedot

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/logos/logo512.png" # Default image for sharing

# Footer nav
navigation_footer:
- title: Alkuun
  url: "#top"
